"""initial tables

Revision ID: 2db1e9f66169
Revises: 
Create Date: 2025-12-30 01:16:58.367140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '2db1e9f66169'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universidades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email_contacto', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('colores_tema', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_universidades_slug'), 'universidades', ['slug'], unique=True)
    op.create_table('carreras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('universidad_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_semestres', sa.Integer(), nullable=True),
    sa.Column('creditos_totales', sa.Integer(), nullable=True),
    sa.Column('mapa_curricular', sa.JSON(), nullable=False),
    sa.Column('grafo_prerrequisitos', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carreras_universidad_id'), 'carreras', ['universidad_id'], unique=False)
    op.create_table('universidad_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('universidad_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('GENERAL', 'REGLAMENTO', 'MATERIA', 'ORGANIGRAMA', 'FAQ', 'ENLACE', 'CALENDARIO', name='tipoinfo'), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('info_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universidad_info_tipo'), 'universidad_info', ['tipo'], unique=False)
    op.create_index(op.f('ix_universidad_info_universidad_id'), 'universidad_info', ['universidad_id'], unique=False)
    op.create_table('estudiantes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('universidad_id', sa.String(length=36), nullable=False),
    sa.Column('carrera_id', sa.String(length=36), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('promedio', sa.Float(), nullable=True),
    sa.Column('creditos_acumulados', sa.Integer(), nullable=True),
    sa.Column('semestre_actual', sa.Integer(), nullable=True),
    sa.Column('situacion_academica', sa.String(length=50), nullable=True),
    sa.Column('kardex_data', sa.JSON(), nullable=True),
    sa.Column('preferencias', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiantes_carrera_id'), 'estudiantes', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_estudiantes_email'), 'estudiantes', ['email'], unique=True)
    op.create_index(op.f('ix_estudiantes_matricula'), 'estudiantes', ['matricula'], unique=False)
    op.create_index(op.f('ix_estudiantes_universidad_id'), 'estudiantes', ['universidad_id'], unique=False)
    op.create_table('sesiones_consultoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estudiante_id', sa.String(length=36), nullable=False),
    sa.Column('universidad_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('HORARIO', 'MATERIAS', 'COMBINADO', 'CHAT', name='tipoconsultoria'), nullable=False),
    sa.Column('estado', sa.Enum('PROCESANDO', 'COMPLETADA', 'ERROR', 'CANCELADA', name='estadosesion'), nullable=False),
    sa.Column('img_oferta_url', sa.String(length=500), nullable=True),
    sa.Column('img_mapa_url', sa.String(length=500), nullable=True),
    sa.Column('img_kardex_url', sa.String(length=500), nullable=True),
    sa.Column('oferta_data', sa.JSON(), nullable=True),
    sa.Column('mapa_data', sa.JSON(), nullable=True),
    sa.Column('kardex_data', sa.JSON(), nullable=True),
    sa.Column('disponibilidad', sa.JSON(), nullable=True),
    sa.Column('creditos_deseados', sa.Integer(), nullable=True),
    sa.Column('horario_recomendado', sa.JSON(), nullable=True),
    sa.Column('materias_sugeridas', sa.JSON(), nullable=True),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.Column('satisfaccion', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_consultoria_estudiante_id'), 'sesiones_consultoria', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_sesiones_consultoria_universidad_id'), 'sesiones_consultoria', ['universidad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesiones_consultoria_universidad_id'), table_name='sesiones_consultoria')
    op.drop_index(op.f('ix_sesiones_consultoria_estudiante_id'), table_name='sesiones_consultoria')
    op.drop_table('sesiones_consultoria')
    op.drop_index(op.f('ix_estudiantes_universidad_id'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_matricula'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_email'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_carrera_id'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_universidad_info_universidad_id'), table_name='universidad_info')
    op.drop_index(op.f('ix_universidad_info_tipo'), table_name='universidad_info')
    op.drop_table('universidad_info')
    op.drop_index(op.f('ix_carreras_universidad_id'), table_name='carreras')
    op.drop_table('carreras')
    op.drop_index(op.f('ix_universidades_slug'), table_name='universidades')
    op.drop_table('universidades')
    # ### end Alembic commands ###
