"""initial_tables

Revision ID: 71f476299e00
Revises: 
Create Date: 2026-01-06 01:49:53.772795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71f476299e00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universidads',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universidads_id'), 'universidads', ['id'], unique=False)
    op.create_index(op.f('ix_universidads_slug'), 'universidads', ['slug'], unique=True)
    op.create_table('carreras',
    sa.Column('universidad_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('total_creditos', sa.String(length=10), nullable=True),
    sa.Column('duracion_semestres', sa.String(length=10), nullable=True),
    sa.Column('plan_estudios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.create_index(op.f('ix_carreras_universidad_id'), 'carreras', ['universidad_id'], unique=False)
    op.create_table('estudiantes',
    sa.Column('universidad_id', sa.UUID(), nullable=False),
    sa.Column('carrera_id', sa.UUID(), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('preferencias', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiantes_carrera_id'), 'estudiantes', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_estudiantes_email'), 'estudiantes', ['email'], unique=True)
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    op.create_index(op.f('ix_estudiantes_matricula'), 'estudiantes', ['matricula'], unique=False)
    op.create_index(op.f('ix_estudiantes_universidad_id'), 'estudiantes', ['universidad_id'], unique=False)
    op.create_table('sesion_consultorias',
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('HORARIO', 'MATERIAS', 'COMBINADO', 'CHAT', name='tipoconsultoria'), nullable=False),
    sa.Column('estado', sa.Enum('INICIADA', 'DOCUMENTOS', 'PROCESANDO', 'COMPLETADA', 'ERROR', name='estadosesion'), nullable=False),
    sa.Column('img_oferta_url', sa.String(length=500), nullable=True),
    sa.Column('img_mapa_url', sa.String(length=500), nullable=True),
    sa.Column('img_kardex_url', sa.String(length=500), nullable=True),
    sa.Column('oferta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapa_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kardex_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disponibilidad', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recomendacion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.Column('calificacion', sa.String(length=1), nullable=True),
    sa.Column('comentario_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesion_consultorias_estudiante_id'), 'sesion_consultorias', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_sesion_consultorias_id'), 'sesion_consultorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesion_consultorias_id'), table_name='sesion_consultorias')
    op.drop_index(op.f('ix_sesion_consultorias_estudiante_id'), table_name='sesion_consultorias')
    op.drop_table('sesion_consultorias')
    op.drop_index(op.f('ix_estudiantes_universidad_id'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_matricula'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_email'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_carrera_id'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_carreras_universidad_id'), table_name='carreras')
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.drop_table('carreras')
    op.drop_index(op.f('ix_universidads_slug'), table_name='universidads')
    op.drop_index(op.f('ix_universidads_id'), table_name='universidads')
    op.drop_table('universidads')
    # ### end Alembic commands ###
